server:
  port: 8084

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/dcms?serverTimezone=UTC&useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  thymeleaf:
    prefix: classpath:/templates/      #模板路径
    suffix: .html                     #模板后缀
    servlet:
      content-type: text/html         #设置 Content-type
    encoding: UTF-8                   #编码方式
    mode: HTML                        #校验HTML5
    cache: false                      #关闭缓存，在开发过程中可立即看到页面修改结果
  mvc:
    static-path-pattern: /**
  mail:
    host: smtp.163.com
    username: 18334758861@163.com
    password: CQUWANBPOAQGPDYL
    default-encoding: UTF-8
mybatis:
  type-aliases-package: com.dcms.pojo
  mapper-locations: classpath:/mapping/*.xml